---
# vim: set ft=ansible:

- name: Copy over k8s-aio env requirements.txt
  ansible.builtin.copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: "Create k8s-aio venv"
  pip:
    requirements: "/tmp/requirements.txt"
    virtualenv: "/opt/virtualenvs/k8s-aio"
    virtualenv_site_packages: true
    virtualenv_command: "/usr/bin/virtualenv"

- name: "Set Ansible interpreter to venv"
  set_fact:
    ansible_python_interpreter: /opt/virtualenvs/k8s-aio/bin/python

- name: Apply OpenShift Advanced Cluster Security Operator
  k8s:
    state: present
    kubeconfig: /root/sno-rhacm/auth/kubeconfig
    definition: "{{ lookup('file', 'acs-operator.yaml') }}"
  register: acs_operator_success
  retries: 5
  delay: 30
  until: acs_operator_success is not failed

- name: Apply ACS Central configuration
  k8s:
    state: present
    kubeconfig: /root/sno-rhacm/auth/kubeconfig
    definition: "{{ lookup('file', 'acs-central.yaml') }}"
  register: central_success
  retries: 5
  delay: 30
  until: central_success is not failed
